### ISSUE TITLE
Can't Open Pal.uproject

### ISSUE THREAD

**Issue by TrepeSerafin** [localcc/PalworldModdingKit#19]
I followed your prerequisites and SDK download steps, but I'm unable to open Pal.uproject. I get different error message every time I try launch it too. 

![Error Messages](https://github.com/localcc/PalworldModdingKit/assets/142684252/3125f03c-197b-4f7a-8ecb-3ea9baf3a013)

I don't know what's going on since I've never used Unreal Engine before. But if I were to guess, I may have messed up SDK download step. I find your Wwise and ThirdParty folder explanation confusing. I copied include, Win32_vc160, Win32_vc170, and etc to PalworldModdingKit-main\Plugins\Wwise\ThirdParty. Am I doing this correctly?

**Comment by TrepeSerafin** [comment]
![image](https://github.com/localcc/PalworldModdingKit/assets/142684252/dc0f9832-0270-42fa-9fe5-e238382ca352)

Yeah, I don't have some files like Intermediate or Config\Windows. How do I fix it?

**Comment by TrepeSerafin** [comment]
![image](https://github.com/localcc/PalworldModdingKit/assets/142684252/0baa3bd2-b533-4a58-b265-4d926e948f30)
![image](https://github.com/localcc/PalworldModdingKit/assets/142684252/e67d41db-55e9-4393-a601-725e62d131ce)

So I redid the SDK and Wwise steps again, and here are some new issues. What should I do?

**Comment by cetusk** [comment]
I have same issue.
I prepared and installed some tools according to this [manual](https://pwmodding.wiki/docs/category/palworld-modding-kit).

I make a note of what I did.

---

Download and installation
- .NET 6
- Visual Studio 2022
- Unreal Engine 5.1 ( my version is 5.1.1 )
- Wwise 2021.1.11.7933 with select 2 packages ( Authoring and C++ SDK ) and 1 platform Visual Studio 2022
- Cloning from this repository using `git clone` command

Integration ( some parts are differenced from the manual )
- Unpack `Unreal.5.1.tar.xz` ( the manual described `Unreal.5.0.tar.xz` but not exist ) and copy `Wwise` folder into `PalworldModdingKit\Plugins`.
- Create `ThirdParty` folder into the `Wwise` and copy 3 folders ( `Win32_vc170`, `x64_vc170` and `include` ) from `Audiokinetic\Wwise 2021.1.11.7933\SDK`, then duplicate `*_vc170` as `*_vc160`.
- Edit `PalworldModdingKit\Plugins\Wwise\Wwise.uplugin` to change the entry `"EngineVersion": "5.1.0",` to `"EngineVersion": "5.1.1",`.

Launching
- Open the Unreal Engine 5.1.1 and open the project `PalworldModdingKit\Pal.uproject`.
- The warning of "Missing Pal Modifiers" then I pressed "Yes".
- The error of "Pal could not compiled".

**Comment by Plamous** [comment]
Same issue here :/ i did the installation multiple times and tried everything that has been said here but with no success. Here is a gif of the problem and my log file. Btw inside my log file I found smth strange maybe it is the source of my problem ( see 2nd screen )

[Pal.log](https://github.com/localcc/PalworldModdingKit/files/14117365/Pal.log)
![Animation](https://github.com/localcc/PalworldModdingKit/assets/157214346/8b601cf7-9195-49b2-92c2-a5de32e442b4)
![image](https://github.com/localcc/PalworldModdingKit/assets/157214346/befd8aae-7f80-41ad-8366-ac25bd291f3d)
 
+ Ive seen multiple files in the project referencing to Unreal engine v5.3 is it ok ?

**Comment by TrepeSerafin** [comment]
Hey, update here. I was able to open it on Unreal Engine by uninstalling and reinstalling .NET, Visual Studio, and Wwise. Perhaps something got set up incorrectly without me noticing. Thanks for the help.

I won't close the issue though, since another user is having the same issue.

**Comment by cetusk** [comment]
@Nixdorfer 
Thanks for your rapid response. I correctly opened the `Pal.uproject` !
( I unzipped the `Wwise.rar` file then replaced the previous folder to it. )

@TrepeSerafin 
Thanks for keep this thread.

**Comment by APlanckFish** [comment]
> I have same issue. I prepared and installed some tools according to this [manual](https://pwmodding.wiki/docs/category/palworld-modding-kit).
> 
> I make a note of what I did.
> 
> Download and installation
> 
> * .NET 6
> * Visual Studio 2022
> * Unreal Engine 5.1 ( my version is 5.1.1 )
> * Wwise 2021.1.11.7933 with select 2 packages ( Authoring and C++ SDK ) and 1 platform Visual Studio 2022
> * Cloning from this repository using `git clone` command
> 
> Integration ( some parts are differenced from the manual )
> 
> * Unpack `Unreal.5.1.tar.xz` ( the manual described `Unreal.5.0.tar.xz` but not exist ) and copy `Wwise` folder into `PalworldModdingKit\Plugins`.
> * Create `ThirdParty` folder into the `Wwise` and copy 3 folders ( `Win32_vc170`, `x64_vc170` and `include` ) from `Audiokinetic\Wwise 2021.1.11.7933\SDK`, then duplicate `*_vc170` as `*_vc160`.
> * Edit `PalworldModdingKit\Plugins\Wwise\Wwise.uplugin` to change the entry `"EngineVersion": "5.1.0",` to `"EngineVersion": "5.1.1",`.
> 
> Launching
> 
> * Open the Unreal Engine 5.1.1 and open the project `PalworldModdingKit\Pal.uproject`.
> * The warning of "Missing Pal Modifiers" then I pressed "Yes".
> * The error of "Pal could not compiled".



> I have same issue. I prepared and installed some tools according to this [manual](https://pwmodding.wiki/docs/category/palworld-modding-kit).
> 
> I make a note of what I did.
> 
> Download and installation
> 
> * .NET 6
> * Visual Studio 2022
> * Unreal Engine 5.1 ( my version is 5.1.1 )
> * Wwise 2021.1.11.7933 with select 2 packages ( Authoring and C++ SDK ) and 1 platform Visual Studio 2022
> * Cloning from this repository using `git clone` command
> 
> Integration ( some parts are differenced from the manual )
> 
> * Unpack `Unreal.5.1.tar.xz` ( the manual described `Unreal.5.0.tar.xz` but not exist ) and copy `Wwise` folder into `PalworldModdingKit\Plugins`.
> * Create `ThirdParty` folder into the `Wwise` and copy 3 folders ( `Win32_vc170`, `x64_vc170` and `include` ) from `Audiokinetic\Wwise 2021.1.11.7933\SDK`, then duplicate `*_vc170` as `*_vc160`.
> * Edit `PalworldModdingKit\Plugins\Wwise\Wwise.uplugin` to change the entry `"EngineVersion": "5.1.0",` to `"EngineVersion": "5.1.1",`.
> 
> Launching
> 
> * Open the Unreal Engine 5.1.1 and open the project `PalworldModdingKit\Pal.uproject`.
> * The warning of "Missing Pal Modifiers" then I pressed "Yes".
> * The error of "Pal could not compiled".

I have the same situation.
How could i fix it?

**Comment by DevAusRod** [comment]
Same issue here.  Unreal build log indicates the issue is due to Wwise. I was very careful to select the correct Wwise installation

![image](https://github.com/localcc/PalworldModdingKit/assets/123772918/0602dc96-6336-4dbe-aed8-3406b0ad71eb)
![image](https://github.com/localcc/PalworldModdingKit/assets/123772918/c2e31e29-31a5-4de7-815c-e9053ea617e4)

`Enabling plugin 'Wwise' (referenced via Pal.uproject)
Expecting to find a type to be declared in a module rules named 'Wwise' in UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.  This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.
BuildException: Expecting to find a type to be declared in a module rules named 'Wwise' in UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.  This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.
   at UnrealBuildTool.RulesAssembly.CreateModuleRules(String ModuleName, ReadOnlyTargetRules Target, String ReferenceChain, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\System\RulesAssembly.cs:line 462
   at UnrealBuildTool.RulesAssembly.CreateModuleRules(String ModuleName, ReadOnlyTargetRules Target, String ReferenceChain, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\System\RulesAssembly.cs:line 394
   at UnrealBuildTool.RulesAssembly.CreateModuleRules(String ModuleName, ReadOnlyTargetRules Target, String ReferenceChain, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\System\RulesAssembly.cs:line 394
   at UnrealBuildTool.UEBuildTarget.CreateModuleRulesAndSetDefaults(String ModuleName, String ReferenceChain, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 4333
   at UnrealBuildTool.UEBuildTarget.FindOrCreateModuleByName(String ModuleName, String ReferenceChain, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 4457
   at UnrealBuildTool.UEBuildTarget.FindOrCreateCppModuleByName(String ModuleName, String ReferenceChain, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 4580
   at UnrealBuildTool.UEBuildTarget.AddPlugin(PluginReferenceDescriptor Reference, String ReferenceChain, String[] ExcludeFolders, Dictionary`2 NameToInstance, Dictionary`2 NameToInfos, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3670
   at UnrealBuildTool.UEBuildTarget.SetupPlugins(ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3463
   at UnrealBuildTool.UEBuildTarget.PreBuildSetup(ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 2677
   at UnrealBuildTool.UEBuildTarget.Create(TargetDescriptor Descriptor, Boolean bSkipRulesCompile, Boolean bForceRulesCompile, Boolean bUsePrecompiled, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 857
   at UnrealBuildTool.BuildMode.CreateMakefile(BuildConfiguration BuildConfiguration, TargetDescriptor TargetDescriptor, ISourceFileWorkingSet WorkingSet, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 741
   at UnrealBuildTool.BuildMode.Build(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger, Boolean bSkipPreBuildTargets) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 275
   at UnrealBuildTool.BuildMode.Execute(CommandLineArguments Arguments, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 242
   at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 648
WriteFileIfChanged() wrote 0 changed files of 0 requested writes.`

Full logs:
Pal Log - [Pal.log](https://github.com/localcc/PalworldModdingKit/files/14214486/Pal.log)
Unreal Build Log - [Log.txt](https://github.com/localcc/PalworldModdingKit/files/14214490/Log.txt)

> Try this https://github.com/Nixdorfer/Public_Storage/blob/main/Storage/Wwise.rar Additionally, if you receive a message like "Unable to compile automatically, please try manually," it may be due to issues with your C++ environment deployment. After performing all the operations, please delete the `Binaries`, `Intermediate`, and `Saved` folders in the project file(not the `…/Plugins/Wwise`, but the project file) and recompile the cache.

It appears your Wwise.rar is gone, so we need to figure something else out.

**Comment by TrepeSerafin** [comment]
I guess the issue is resolved. Closing the issue.
